print("This", end=" ")
print("is", end=" ")
print("an", end=" ")
print("example")
print("of")
print("how", end=" ")
print("we", end=" ")
print("can", end=" ")
print("customize", end=" ")
print("our", end=" ")
print("printing!")
